"""create tasks table

Revision ID: 79790841b2bc
Revises: db0cf72fa220
Create Date: 2025-12-29 20:57:07.094358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79790841b2bc'
down_revision: Union[str, Sequence[str], None] = 'db0cf72fa220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_At', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tasks_id'), 'Tasks', ['id'], unique=False)
    op.create_index(op.f('ix_Tasks_status'), 'Tasks', ['status'], unique=False)
    op.create_index(op.f('ix_Tasks_title'), 'Tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_title'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_status'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_id'), table_name='Tasks')
    op.drop_table('Tasks')
    # ### end Alembic commands ###
